# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CourtNotifier.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CourtNotifier(object):
    def setupUi(self, CourtNotifier):
        CourtNotifier.setObjectName("CourtNotifier")
        CourtNotifier.resize(271, 190)
        self.verticalLayoutWidget = QtWidgets.QWidget(CourtNotifier)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_to = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_to.setObjectName("lineEdit_to")
        self.horizontalLayout.addWidget(self.lineEdit_to)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_account = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.horizontalLayout_2.addWidget(self.lineEdit_account)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_3.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_interval = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_interval.setObjectName("lineEdit_interval")
        self.horizontalLayout_4.addWidget(self.lineEdit_interval)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_test = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_test.setObjectName("button_test")
        self.horizontalLayout_5.addWidget(self.button_test)
        self.button_start = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_start.setObjectName("button_start")
        self.horizontalLayout_5.addWidget(self.button_start)
        self.button_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_5.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(CourtNotifier)
        QtCore.QMetaObject.connectSlotsByName(CourtNotifier)

    def retranslateUi(self, CourtNotifier):
        _translate = QtCore.QCoreApplication.translate
        CourtNotifier.setWindowTitle(_translate("CourtNotifier", "西松高中布告欄更新通知工具"))
        self.label.setText(_translate("CourtNotifier", "收件人Email"))
        self.label_2.setText(_translate("CourtNotifier", "寄件人帳號"))
        self.label_3.setText(_translate("CourtNotifier", "寄件人密碼"))
        self.label_4.setText(_translate("CourtNotifier", "間隔時間"))
        self.button_test.setText(_translate("CourtNotifier", "Test"))
        self.button_start.setText(_translate("CourtNotifier", "Start"))
        self.button_cancel.setText(_translate("CourtNotifier", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CourtNotifier = QtWidgets.QWidget()
    ui = Ui_CourtNotifier()
    ui.setupUi(CourtNotifier)
    CourtNotifier.show()
    sys.exit(app.exec_())
